version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # If you're using Create React App and want hot reloading to work on Docker
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.compose
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - GO_ENV=development
